D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.IF.deps.json
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.IF.dll
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.IF.pdb
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.DO.dll
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.DO.pdb
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.csprojAssemblyReference.cache
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.csproj.CoreCompileInputs.cache
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.AssemblyInfoInputs.cache
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.AssemblyInfo.cs
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.csproj.CopyComplete
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.dll
D:\OfficeWorkingProjects\WebProjects\ESYAProject_WorkingUI&WEBAPI\Working_AlleSyaWebAPI\eSyaLocalizationWebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.pdb
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.IF.deps.json
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.IF.dll
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.IF.pdb
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.DO.dll
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\bin\Debug\netcoreapp2.2\NG.Localization.DO.pdb
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.csprojAssemblyReference.cache
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.csproj.CoreCompileInputs.cache
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.AssemblyInfoInputs.cache
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.AssemblyInfo.cs
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.csproj.CopyComplete
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.dll
D:\OfficeWorkingProjects\AllWEBAPI\eSyaLocalize.WebAPI\NG.Localization.WebAPI\eSyaLocalization.IF\obj\Debug\netcoreapp2.2\NG.Localization.IF.pdb
